### PR TITLE
Fix supportLS function always returning true

### LINKED ISSUE #11: The supportLS function returns incorrect value for browsers that do not support localstorage
## Expected Behavior
The `supportLS` function should return `false` when a browser doesn't support `localstorage`.

## Current Behavior
The `supportLS` function always return `true`, as the `hasLS = true` assignment happens after the try/catch block, which overwrites the value of `hasLS` when it is `false`.

## Steps to Reproduce (for bugs)
Not provided, but bug is obvious by looking at the code.

### PR DESCRIPTION
**Pull request by rostow**
The `supportLS` function currently returns `true` even for browsers that do not support `localstorage`.

This PR fixes the issue by moving the `hasLS = true` assignment inside the try block, to avoid overwriting the value of the `hasLS` variable in the cases where there is no browser support.

Fixes #11

### CODE REVIEW

File: src/ls.ts [hunk 1]
```diff
@@ -17,12 +17,12 @@ const supportsLS = (): boolean => {
     if (!localStorage) {
       hasLS = false;
     }
+    hasLS = true;
```
Comment (niketpathak) [inline src/ls.ts:20]: Thank you for pointing out the bug. I think this line should come before line 17. Because by placing it here, it suffers from the same problem as before. (i.e. It will always be set to `true`)

Comment (niketpathak) [reply src/ls.ts]: I have done the needful. Thanks again!

Comment (rostow) [reply src/ls.ts]: Apologies for the slow response. Indeed that was a brain fart of mine! Thanks for fixing 😁
